#!/usr/bin/env bun
/**
 * Generate src/palettes/ncs.ts from the Color-Names Raku module's
 * NCS dataset by @thundergnat on GitHub.
 *
 * NCS (Natural Colour System) is a Swedish perceptual color
 * standard based on Hering's opponent-process theory: six
 * elementary colors (W, S, Y, R, B, G) and codes like
 * '0500-N' (neutral gray 5% blackness) or '2030-R80B' (20%
 * blackness, 30% chromaticness, red hue 80% toward blue).
 * Widely used in Scandinavian design, architecture, and paint
 * manufacturing.
 *
 * Canonical key format: the NCS code as published, e.g.
 * '0500-N' or '2030-R80B'. This is the "codes-as-names"
 * pattern chromonym already uses for Pantone ('185 C') and
 * Federal Standard 595 ('FS 11136'). `standardNormalize`
 * strips the dash and casing so 'NCS 2030-R80B', '2030r80b',
 * and '2030 R80B' all resolve identically.
 *
 * NCS is DEVICE-INDEPENDENT by design; any sRGB approximation
 * is lossy. These values match the thundergnat Raku module's
 * digitization. See NOTICE.md for attribution and trademark.
 *
 * Usage: bun run scripts/generate-ncs.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { rgbaToHex } from '../src/conversions/hex.js';

const SOURCE =
  'https://raw.githubusercontent.com/thundergnat/Color-Names/refs/heads/main/lib/Color/Names/NCS.rakumod';
const TARGET = resolve(import.meta.dirname, '../src/palettes/ncs.ts');

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const response = await fetch(SOURCE);
if (!response.ok) {
  throw new Error(`Failed to fetch ${SOURCE}: ${response.status}`);
}
const text = await response.text();

// '0500n-NCS' => { rgb => [0xf2, 0xf2, 0xf2], name => ｢0500-N｣, code => '0500-N' },
// Both `name` (in ｢｣) and `code` (in '') carry the same NCS notation; we use
// the `name` field for the display key since it's the one that preserves
// Raku string semantics. The raku identifier is the lowercased-compacted
// form and is only used indirectly via dedupe.
const ENTRY_RE =
  /'([a-z0-9]+)-NCS'\s*=>\s*\{\s*rgb\s*=>\s*\[0x([0-9A-Fa-f]{1,2}),\s*0x([0-9A-Fa-f]{1,2}),\s*0x([0-9A-Fa-f]{1,2})\]\s*,\s*name\s*=>\s*｢([^｣]+)｣/g;

// Key: normalized form (used for dedupe). Value: [displayKey, hex].
const entries = new Map<string, [string, string]>();
let match: RegExpExecArray | null;
// biome-ignore lint/suspicious/noAssignInExpressions: standard global-regex loop pattern
while ((match = ENTRY_RE.exec(text)) !== null) {
  const [, , rStr, gStr, bStr, displayName] = match;
  const r = Number.parseInt(rStr, 16);
  const g = Number.parseInt(gStr, 16);
  const b = Number.parseInt(bStr, 16);
  const hex = rgbaToHex({ r, g, b, a: 1 });
  const key = normalize(displayName);
  const existing = entries.get(key);
  if (existing !== undefined && existing[1] !== hex) {
    console.warn(
      `collision for "${key}": kept ${existing[1]} (${existing[0]}), ignored ${hex} (${displayName})`,
    );
    continue;
  }
  if (existing === undefined) entries.set(key, [displayName.trim(), hex]);
}

if (entries.size === 0) {
  throw new Error('No entries parsed from NCS source; regex may be out of date.');
}

// Sort by normalized key so '0300-N', '0500-N', '0502-B', '0502-B50G' land
// in natural NCS reading order.
const sorted = [...entries.values()].sort(([a], [b]) => normalize(a).localeCompare(normalize(b)));

// NCS codes always contain non-identifier characters (dashes and digits
// leading), so every emitted key will be quoted.
const SIMPLE_IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;
const formatKey = (k: string) => (SIMPLE_IDENT.test(k) ? k : JSON.stringify(k));

const body = sorted.map(([name, hex]) => `  ${formatKey(name)}: '${hex}',`).join('\n');

const output = `import type { Palette } from '../types.js';

// NCS codes are often written with a leading 'NCS' brand prefix and/or
// a leading 'S ' (for "Standard NCS"), e.g. 'NCS S 2030-R80B'. Strip
// both during normalization so 'NCS S 2030-R80B', 'S 2030-R80B',
// '2030-R80B', and '2030r80b' all resolve to the same entry. The 'S'
// prefix is only stripped when followed by a digit so it doesn't eat
// the leading character of unrelated inputs.
const NCS_PREFIX_RE = /^ncs/;
const NCS_STANDARD_RE = /^s(?=\\d)/;
function ncsNormalize(input: string): string {
  const stripped = input.toLowerCase().replace(/[^a-z0-9]/g, '');
  return stripped.replace(NCS_PREFIX_RE, '').replace(NCS_STANDARD_RE, '');
}

/**
 * Natural Colour System (NCS) palette: the Swedish perceptual
 * color standard based on Hering's opponent-process theory.
 * ${sorted.length} entries covering the 1950-chip NCS Atlas,
 * named by their NCS notation ('0500-N' for neutral gray 5%
 * blackness, '2030-R80B' for 20/30 red-80-blue, etc.).
 *
 * Generated by scripts/generate-ncs.ts — do not edit by hand.
 *
 * NCS is widely used in Scandinavian design, architecture, and
 * paint manufacturing. The system is DEVICE-INDEPENDENT by
 * design; any sRGB approximation is lossy. These values match
 * the thundergnat Raku module's digitization. See NOTICE.md
 * for attribution and the NCS trademark notice.
 *
 * Keys are the NCS codes with their canonical dash ('0500-N'),
 * matching the codes-as-names convention already used by
 * \`pantone\` ('185 C') and \`fs595c\` ('FS 11136'). Lookups still
 * accept any casing and punctuation via standardNormalize, so
 * 'ncs 2030-R80B', '2030r80b', and '2030 R80B' all resolve
 * identically.
 */
const ncsColors = {
${body}
} as const;

export type NcsColorName = keyof typeof ncsColors;

/**
 * NCS palette with perceptual CIEDE2000 default: dense coverage
 * across the full gamut including many closely-spaced hues in
 * the saturated regions where ΔE76 is a known weak spot.
 *
 * @example
 * identify('#f2f2f2', { palette: ncs });           // '0500-N' (neutral gray)
 * resolve('0500-N', { palette: ncs });             // '#f2f2f2'
 * resolve('ncs 0500 N', { palette: ncs });         // '#f2f2f2' (normalized)
 * ncs.colors['2030-R80B'];                         // a moderate red-blue
 */
export const ncs = {
  name: 'ncs',
  colors: ncsColors,
  normalize: ncsNormalize,
  defaultMetric: 'deltaE2000',
} as const satisfies Palette<NcsColorName>;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${sorted.length} NCS colors to ${TARGET}`);
