#!/usr/bin/env bun
/**
 * Generate src/palettes/isccNbs.ts from Paul Centore's ISCC-NBS
 * Colour System page. Scrapes the HTML table that lays out all 267
 * ISCC-NBS Level 3 named color blocks with their sRGB centroids.
 *
 * ISCC-NBS (Inter-Society Color Council / National Bureau of
 * Standards) is a 1955 US standard that partitions the Munsell
 * color solid into 267 named blocks ("vivid pink", "strong purplish
 * red", "dark yellowish brown"). Widely used in color-science
 * literature; see NOTICE.md for attribution details.
 *
 * The scraped page renders light colors with a bare `&nbsp<name>` in
 * each `align="left"` cell, and dark colors with an extra `<FONT
 * COLOR="white">` wrapper so the label stays readable. The single
 * regex below handles both variants.
 *
 * Eats its own dogfood for the RGB → hex step: imports `rgbaToHex`
 * from the library rather than reimplementing a hex-pad-join.
 *
 * Usage: bun run scripts/generate-iscc-nbs.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { rgbaToHex } from '../src/conversions/hex.js';

const SOURCE =
  'https://www.munsellcolorscienceforpainters.com/ISCCNBS/ISCCNBSSystem.html';
const TARGET = resolve(import.meta.dirname, '../src/palettes/isccNbs.ts');

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const response = await fetch(SOURCE);
if (!response.ok) {
  throw new Error(`Failed to fetch ${SOURCE}: ${response.status}`);
}
const html = await response.text();

// Light cells:  <td style="bg:rgb(...)" align="left">&nbsp<name></FONT></td>
// Dark cells:   <td style="bg:rgb(...)" align="left"><FONT COLOR="white">&nbsp<name></FONT></td>
// The &nbsp is a literal entity (no semicolon in this page's source).
const CELL_RE =
  /<td\s+style="background-color:rgb\((\d+),\s*(\d+),\s*(\d+)\)"\s+align="left">(?:<FONT[^>]*>)?&nbsp\s?([^<]+?)<\/FONT><\/td>/g;

// Separately capture the out-of-gamut (NaN RGB) entries so we can log them.
// Centore's page uses rgb(NaN,NaN,NaN) for Munsell blocks whose centroids
// fall outside the sRGB gamut and therefore have no valid approximation.
const NAN_CELL_RE =
  /<td\s+style="background-color:rgb\(NaN,\s*NaN,\s*NaN\)"\s+align="left">(?:<FONT[^>]*>)?&nbsp\s?([^<]+?)<\/FONT><\/td>/g;
const nanNames: string[] = [];
let nanMatch: RegExpExecArray | null;
// biome-ignore lint/suspicious/noAssignInExpressions: standard global-regex loop pattern
while ((nanMatch = NAN_CELL_RE.exec(html)) !== null) {
  nanNames.push(nanMatch[1].trim());
}

// Key: normalized form (used for dedupe). Value: [displayName, hex].
const entries = new Map<string, [string, string]>();
let match: RegExpExecArray | null;
// biome-ignore lint/suspicious/noAssignInExpressions: standard global-regex loop pattern
while ((match = CELL_RE.exec(html)) !== null) {
  const [, rStr, gStr, bStr, rawName] = match;
  const r = Number.parseInt(rStr, 10);
  const g = Number.parseInt(gStr, 10);
  const b = Number.parseInt(bStr, 10);
  if (!Number.isFinite(r) || !Number.isFinite(g) || !Number.isFinite(b)) continue;
  const name = rawName.trim();
  if (!name) continue;
  const hex = rgbaToHex({ r, g, b, a: 1 });
  const key = normalize(name);
  const existing = entries.get(key);
  if (existing !== undefined && existing[1] !== hex) {
    console.warn(
      `collision for "${key}": kept ${existing[1]} (${existing[0]}), ignored ${hex} (${name})`,
    );
    continue;
  }
  if (existing === undefined) entries.set(key, [name, hex]);
}

if (entries.size === 0) {
  throw new Error(
    'No entries parsed from ISCC-NBS source; regex may be out of date or the page structure changed.',
  );
}

// Sort alphabetically by display name for a stable emit order.
const sorted = [...entries.values()].sort(([a], [b]) => a.localeCompare(b));

// JSON.stringify handles the spaces in multi-word display names robustly.
const SIMPLE_IDENT = /^[a-z_][a-z0-9_]*$/;
const formatKey = (k: string) => (SIMPLE_IDENT.test(k) ? k : JSON.stringify(k));

const body = sorted.map(([name, hex]) => `  ${formatKey(name)}: '${hex}',`).join('\n');

const output = `import type { Palette } from '../types.js';
import { standardNormalize } from './normalize.js';

/**
 * ISCC-NBS palette (${sorted.length} entries): the Inter-Society
 * Color Council / National Bureau of Standards 1955 method of
 * designating colors, which partitions the Munsell color solid
 * into named blocks like 'vivid pink', 'strong purplish red',
 * 'dark yellowish brown'. Widely used in color-science literature
 * as a standard vocabulary for consistent color communication.
 *
 * Generated by scripts/generate-iscc-nbs.ts — do not edit by hand.
 *
 * Source: Paul Centore's Munsell Colour Science for Painters
 * site, ISCCNBSSystem.html — sRGB centroids of each named block.
 * See NOTICE.md for attribution and license notes.
 *
 * Keys are sentence-case display names ('Vivid pink') matching
 * the ISCC-NBS vocabulary. Lookups still accept any casing or
 * punctuation via standardNormalize, so 'vivid-pink' and
 * 'VIVID PINK' both resolve identically.
 */
const isccNbsColors = {
${body}
} as const;

export type IsccNbsColorName = keyof typeof isccNbsColors;

/**
 * ISCC-NBS Method of Designating Colors (1955, ${sorted.length}
 * entries): Munsell-partitioned named blocks like 'Vivid pink'
 * and 'Dark yellowish brown'. sRGB centroids computed by Paul
 * Centore. For the alternate digitization that matches the
 * 1955 physical chip book, see chromonym's \`nbs\` palette.
 * Default metric CIEDE2000.
 *
 * @example
 * identify('#fd7992', { palette: isccNbs });           // 'Vivid pink'
 * resolve('dark yellowish green', { palette: isccNbs }); // '#2f5d3a'
 * isccNbs.colors['Vivid pink'];                          // '#fd7992'
 */
export const isccNbs = {
  name: 'isccNbs',
  colors: isccNbsColors,
  normalize: standardNormalize,
  defaultMetric: 'deltaE2000',
} as const satisfies Palette<IsccNbsColorName>;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${sorted.length} ISCC-NBS colors to ${TARGET}`);
if (nanNames.length > 0) {
  console.log(
    `Skipped ${nanNames.length} out-of-sRGB-gamut entries (no valid centroid):`,
  );
  for (const n of nanNames) console.log(`  - ${n}`);
}
