#!/usr/bin/env bun
/**
 * Generate src/colorspaces/x11.ts from the X.Org rgb.txt file.
 *
 * Reads from /usr/share/X11/rgb.txt (X11 / X.Org public-domain color list).
 * Normalizes names to lowercase with spaces removed, dedupes on identical
 * (key, value) pairs, sorts alphabetically, emits as a typed Colorspace.
 *
 * Usage: bun run scripts/generate-x11.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SOURCE = '/usr/share/X11/rgb.txt';
const TARGET = resolve(import.meta.dirname, '../src/colorspaces/x11.ts');

const toHex = (r: number, g: number, b: number): string =>
  `#${[r, g, b].map((n) => n.toString(16).padStart(2, '0')).join('')}`;

const raw = readFileSync(SOURCE, 'utf8');

const entries = new Map<string, string>();
for (const line of raw.split('\n')) {
  if (!line || line.startsWith('!')) continue;
  const match = /^\s*(\d+)\s+(\d+)\s+(\d+)\s+(.+?)\s*$/.exec(line);
  if (!match) continue;
  const [, r, g, b, rawName] = match;
  const name = rawName.toLowerCase().replace(/\s+/g, '');
  const hex = toHex(Number(r), Number(g), Number(b));
  const existing = entries.get(name);
  if (existing !== undefined && existing !== hex) {
    // Collision with different value — warn, keep first.
    console.warn(`collision for "${name}": kept ${existing}, ignored ${hex}`);
    continue;
  }
  if (existing === undefined) entries.set(name, hex);
}

const sorted = [...entries.entries()].sort(([a], [b]) => a.localeCompare(b));

const body = sorted.map(([name, hex]) => `  ${name}: '${hex}',`).join('\n');

const output = `import type { Colorspace } from '../types';

/**
 * X11 / X.Org named colors (from rgb.txt, public domain).
 * Generated by scripts/generate-x11.ts — do not edit by hand.
 * Names normalized to lowercase, spaces removed.
 */
export const x11 = {
${body}
} as const satisfies Colorspace;

export type X11ColorName = keyof typeof x11;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${sorted.length} X11 colors to ${TARGET}`);
