#!/usr/bin/env bun

/**
 * Generate src/palettes/pantone.ts from the color_library package.
 *
 * Reads the Pantone array from color_library (MIT © Radu Dragan),
 * extracts Coated ("C" suffix) entries, converts RGB -> hex, sorts by
 * numeric code, emits as a typed Palette.
 *
 * Pantone values are trademarked; these are community approximations,
 * not official Pantone measurements.
 *
 * Usage:
 *   bun add -D color_library   # one-time (or `npm install -D color_library`)
 *   bun run scripts/generate-pantone.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { resolve } from 'node:path';

const TARGET = resolve(import.meta.dirname, '../src/palettes/pantone.ts');

const require_ = createRequire(import.meta.url);

let SOURCE: string;
try {
  SOURCE = require_.resolve('color_library');
} catch {
  console.error(
    'color_library not found. Install it as a devDependency first:\n' +
      '  bun add -D color_library',
  );
  process.exit(1);
}

const toHex = (r: number, g: number, b: number): string =>
  `#${[r, g, b].map((n) => n.toString(16).padStart(2, '0')).join('')}`;

const raw = readFileSync(SOURCE, 'utf8');

// Narrow to the pantone array block.
const pantoneBlockMatch = /pantone:\s*\[([\s\S]*?)\n {4}\],/.exec(raw);
if (!pantoneBlockMatch) throw new Error('Pantone block not found in source');
const block = pantoneBlockMatch[1];
if (!block) throw new Error('Pantone block matched but empty');

// `[\s\S]*?` (non-greedy, any char) is needed to skip past the CMYK
// block's `}` before matching `rgb:{`.
const entryRe =
  /\{\s*name:"([^"]+)"[\s\S]*?rgb:\{\s*"r":\s*(\d+)\s*,\s*"g":\s*(\d+)\s*,\s*"b":\s*(\d+)\s*\}/g;

// Humanize raw names so keys are readable: '185C' → '185 C', 'Black2C' → 'Black 2 C'.
// Identify uses these keys as display names; resolve still accepts any spelling
// since pantoneNormalize strips spaces and prefixes before lookup.
const humanize = (name: string) =>
  name
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Za-z])(\d)/g, '$1 $2')
    .replace(/(\d)([A-Za-z])/g, '$1 $2')
    .replace(/\s+/g, ' ')
    .trim();

const entries = new Map<string, string>();
let m: RegExpExecArray | null;
// biome-ignore lint/suspicious/noAssignInExpressions: standard RegExp.exec loop
while ((m = entryRe.exec(block)) !== null) {
  const [, name, r, g, b] = m;
  if (!name || !r || !g || !b) continue;
  entries.set(humanize(name), toHex(Number(r), Number(g), Number(b)));
}

// Sort by leading numeric value, then by full key.
const sorted = [...entries.entries()].sort(([a], [b]) => {
  const na = Number.parseInt(a, 10);
  const nb = Number.parseInt(b, 10);
  if (na !== nb) return na - nb;
  return a.localeCompare(b);
});

const body = sorted.map(([name, hex]) => `  '${name}': '${hex}',`).join('\n');

const output = `import type { Palette } from '../types';
import { pantoneNormalize } from './normalize';

/**
 * Pantone Coated (C) colors — community approximations. ${sorted.length} entries.
 * Source: color_library (MIT © Radu Dragan, https://github.com/draganradu/color_library).
 * Generated by scripts/generate-pantone.ts — do not edit by hand.
 *
 * NOTE: Pantone is a registered trademark. These values are open-source
 * approximations, not official Pantone-licensed measurements.
 */
const pantoneColors = {
${body}
} as const;

export type PantoneColorName = keyof typeof pantoneColors;

export const pantone = {
  name: 'pantone',
  colors: pantoneColors,
  normalize: pantoneNormalize,
  defaultMetric: 'deltaE2000',
} as const satisfies Palette<PantoneColorName>;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${sorted.length} Pantone Coated colors to ${TARGET}`);
