#!/usr/bin/env bun
/**
 * Generate src/palettes/fs595b.ts from the Color-Names Raku module's
 * FS595B dataset by @thundergnat on GitHub.
 *
 * FS595B ("Federal Standard 595B") is the 1989 revision of the US
 * Federal Government's paint-color specification, later superseded
 * by FS595C (2008). Same 5-digit coding scheme; different hex
 * values on some shared codes. Widely referenced by modelers,
 * restorers, and historical-equipment enthusiasts where the B
 * revision was in force.
 *
 * Canonical key format: `'FS ${code}'` (e.g. `'FS 11136'`), same
 * as the FS595C palette. Common names are NOT used as keys (the
 * spec reuses many of them across different chips, 20 different
 * "Green"s etc.), but are captured as trailing comments on each
 * emitted entry so human readers of the generated file see the
 * common name alongside the code.
 *
 * Usage: bun run scripts/generate-fs595b.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SOURCE =
  'https://raw.githubusercontent.com/thundergnat/Color-Names/refs/heads/main/lib/Color/Names/FS595B.rakumod';
const TARGET = resolve(import.meta.dirname, '../src/palettes/fs595b.ts');

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const response = await fetch(SOURCE);
if (!response.ok) {
  throw new Error(`Failed to fetch ${SOURCE}: ${response.status}`);
}
const text = await response.text();

// '10140-FS595B' => { rgb => [0x53, 0x2F, 0x15], name => ｢10140｣, code => ｢Brown Special｣ },
// The `code => ｢...｣` field holds the common name (may be empty).
const ENTRY_RE =
  /'(\d+)-FS595B'\s*=>\s*\{\s*rgb\s*=>\s*\[0x([0-9A-Fa-f]{1,2}),\s*0x([0-9A-Fa-f]{1,2}),\s*0x([0-9A-Fa-f]{1,2})\][^}]*code\s*=>\s*｢([^｣]*)｣/g;

const toHexByte = (s: string) => s.padStart(2, '0').toLowerCase();

// Key: normalized form (used for dedupe). Value: [displayKey, hex, commonName].
const entries = new Map<string, [string, string, string]>();
let match: RegExpExecArray | null;
// biome-ignore lint/suspicious/noAssignInExpressions: standard global-regex loop pattern
while ((match = ENTRY_RE.exec(text)) !== null) {
  const [, code, r, g, b, commonName] = match;
  const displayKey = `FS ${code}`;
  const hex = `#${toHexByte(r)}${toHexByte(g)}${toHexByte(b)}`;
  const key = normalize(displayKey);
  const existing = entries.get(key);
  if (existing !== undefined && existing[1] !== hex) {
    console.warn(
      `collision for "${key}": kept ${existing[1]} (${existing[0]}), ignored ${hex} (${displayKey})`,
    );
    continue;
  }
  if (existing === undefined) entries.set(key, [displayKey, hex, commonName.trim()]);
}

if (entries.size === 0) {
  throw new Error('No entries parsed from FS595B source; regex may be out of date.');
}

// Sort numerically by FS code so the emitted file reads in code order.
const sorted = [...entries.values()].sort(([a], [b]) => {
  const na = Number.parseInt(a.slice(3), 10);
  const nb = Number.parseInt(b.slice(3), 10);
  return na - nb;
});

const SIMPLE_IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;
const formatKey = (k: string) => (SIMPLE_IDENT.test(k) ? k : JSON.stringify(k));

const body = sorted
  .map(([name, hex, commonName]) => {
    const base = `  ${formatKey(name)}: '${hex}',`;
    return commonName ? `${base} // ${commonName}` : base;
  })
  .join('\n');

const namedCount = sorted.filter(([, , common]) => common).length;

const output = `import type { Palette } from '../types.js';
import { standardNormalize } from './normalize.js';

/**
 * Federal Standard 595B (FS595B) palette: the 1989 revision of the
 * US Federal Government paint-color specification. Superseded by
 * FS595C in 2008 but still referenced by modelers and restorers
 * for equipment documented against the B revision. ${sorted.length} entries.
 *
 * Generated by scripts/generate-fs595b.ts — do not edit by hand.
 *
 * Source: upstream dataset is Color::Names::FS595B from
 * @thundergnat/Color-Names (Raku module), which digitizes the
 * published Federal Standard paint chips. See NOTICE.md.
 *
 * Keys are the 5-digit FS codes prefixed with 'FS ' (e.g.
 * 'FS 11136'), matching the FS595C palette's convention. Common
 * names ("Brown Special", "Insignia Red", etc.) are captured as
 * trailing comments for human readers but are NOT unique (the
 * spec reuses many across different chips) so they are not used
 * as lookup keys. ${namedCount} of ${sorted.length} entries carry
 * a common name in the upstream data.
 *
 * Same-coded chips can differ in hex between the B and C
 * revisions; for example 'FS 11136' ('Insignia Red') is
 * ${sorted.find(([n]) => n === 'FS 11136')?.[1] ?? '(missing)'} in this palette versus a slightly different
 * value in FS595C. Pick whichever matches your reference
 * documentation.
 */
const fs595bColors = {
${body}
} as const;

export type Fs595bColorName = keyof typeof fs595bColors;

/**
 * FS595B palette with perceptual CIEDE2000 default.
 *
 * @example
 * identify('#9b2f25', { palette: fs595b });       // 'FS 11136' (aka "Insignia Red")
 * resolve('FS 11136', { palette: fs595b });       // '#9b2f25'
 * fs595b.colors['FS 10140'];                      // '#532f15' (aka "Brown Special")
 */
export const fs595b = {
  name: 'fs595b',
  colors: fs595bColors,
  normalize: standardNormalize,
  defaultMetric: 'deltaE2000',
} as const satisfies Palette<Fs595bColorName>;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(
  `Wrote ${sorted.length} FS595B colors to ${TARGET} (${namedCount} annotated with common names)`,
);
