#!/usr/bin/env bun
/**
 * Generate src/palettes/xkcd.ts from the XKCD color-survey results.
 *
 * Source: <https://xkcd.com/color/rgb.txt>, released by Randall
 * Munroe under CC0 1.0 Universal (public domain dedication; see
 * the header line in the source file).
 *
 * Format is tab-separated `name\t#hex\t` per line, with a leading
 * `#`-prefixed comment line carrying the license URL. Names are
 * already lowercase with spaces ("cloudy blue"), matching x11's
 * display convention.
 *
 * Dedupe is by `standardNormalize(name)` just like the other
 * generators; the source has no duplicates as of the 2010 survey,
 * but the check is here as a safety net.
 *
 * Usage: bun run scripts/generate-xkcd.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SOURCE = 'https://xkcd.com/color/rgb.txt';
const TARGET = resolve(import.meta.dirname, '../src/palettes/xkcd.ts');

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const response = await fetch(SOURCE);
if (!response.ok) {
  throw new Error(`Failed to fetch ${SOURCE}: ${response.status}`);
}
const text = await response.text();

// Key: normalized form (used for dedupe). Value: [displayName, hex].
const entries = new Map<string, [string, string]>();
for (const rawLine of text.split('\n')) {
  const line = rawLine.trim();
  // Skip the license-header comment and any blank lines.
  if (!line || line.startsWith('#') || line.startsWith('!')) continue;
  const parts = line
    .split('\t')
    .map((p) => p.trim())
    .filter(Boolean);
  if (parts.length < 2) continue;
  const [name, hexRaw] = parts;
  if (!name || !hexRaw) continue;
  const hex = hexRaw.toLowerCase();
  if (!/^#[0-9a-f]{6}$/.test(hex)) {
    console.warn(`skipping malformed entry "${name}" → "${hexRaw}"`);
    continue;
  }
  const key = normalize(name);
  const existing = entries.get(key);
  if (existing !== undefined && existing[1] !== hex) {
    console.warn(
      `collision for "${key}": kept ${existing[1]} (${existing[0]}), ignored ${hex} (${name})`,
    );
    continue;
  }
  if (existing === undefined) entries.set(key, [name, hex]);
}

const sorted = [...entries.values()].sort(([a], [b]) => a.localeCompare(b));

// JSON.stringify handles embedded apostrophes and whitespace safely.
const SIMPLE_IDENT = /^[a-z_][a-z0-9_]*$/;
const formatKey = (k: string) => (SIMPLE_IDENT.test(k) ? k : JSON.stringify(k));

const body = sorted.map(([name, hex]) => `  ${formatKey(name)}: '${hex}',`).join('\n');

const output = `import type { Palette } from '../types.js';
import { standardNormalize } from './normalize.js';

/**
 * XKCD color-survey palette (${sorted.length} entries): results
 * of Randall Munroe's 2010 "Color Survey," released to the public
 * domain under CC0. Names are the most-common crowd-sourced name
 * for each color, including weird ones ("poo brown", "baby puke
 * green"). Keys are lowercase with spaces.
 *
 * Generated by scripts/generate-xkcd.ts — do not edit by hand.
 *
 * Source: <https://xkcd.com/color/rgb.txt>. See NOTICE.md for
 * attribution details.
 */
const xkcdColors = {
${body}
} as const;

export type XkcdColorName = keyof typeof xkcdColors;

/**
 * XKCD 2010 Color Survey: crowd-sourced common-speech color
 * names (${sorted.length} entries, CC0 public domain). Earthy,
 * muted, and sometimes irreverent ('baby puke green', 'poo
 * brown'). Default metric CIEDE2000 for consistent nearest-
 * match behavior across the survey's full-gamut coverage.
 *
 * @example
 * identify('#b2996e', { palette: xkcd });          // 'dust'
 * resolve('cloudy blue', { palette: xkcd });       // '#acc2d9'
 * xkcd.colors['baby puke green'];                  // '#b6c406'
 */
export const xkcd = {
  name: 'xkcd',
  colors: xkcdColors,
  normalize: standardNormalize,
  defaultMetric: 'deltaE2000',
} as const satisfies Palette<XkcdColorName>;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${sorted.length} XKCD colors to ${TARGET}`);
