#!/usr/bin/env bun
/**
 * Generate src/palettes/resene.ts from the Color-Names Raku module's
 * Resene dataset by @thundergnat on GitHub.
 *
 * Resene is a New Zealand paint company with a large catalog of
 * named colors, many with distinctly local flavor ("Acapulco,"
 * "Pohutukawa," "Afghan Tan"). The Raku module ships one entry
 * per Resene color with three useful fields:
 *
 *   'treepoppy-RESENE' => {
 *     rgb => [0xFC, 0x6C, 0x27],
 *     name => ｢Tree Poppy｣,           // display form
 *     code => 'BR32-011-076'          // Resene's Munsell-style code
 *   }
 *
 * Canonical keys use the stripped lowercase raku form ('treepoppy')
 * so the palette follows a CSS-like keyword convention; the display
 * name ("Tree Poppy") and Resene code ("BR32-011-076") are emitted
 * as trailing comments on each entry for human readers.
 *
 * Usage: bun run scripts/generate-resene.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { rgbaToHex } from '../src/conversions/hex.js';

const SOURCE =
  'https://raw.githubusercontent.com/thundergnat/Color-Names/refs/heads/main/lib/Color/Names/Resene.rakumod';
const TARGET = resolve(import.meta.dirname, '../src/palettes/resene.ts');

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const response = await fetch(SOURCE);
if (!response.ok) {
  throw new Error(`Failed to fetch ${SOURCE}: ${response.status}`);
}
const text = await response.text();

// '<stripped>-RESENE' => { rgb => [0xRR, 0xGG, 0xBB], name => ｢<display>｣, code => '<resene-code>' }
// The `name` is wrapped in Raku's ｢｣ delimiters; `code` is single-quoted.
const ENTRY_RE =
  /'([a-z0-9]+)-RESENE'\s*=>\s*\{\s*rgb\s*=>\s*\[0x([0-9A-Fa-f]{1,2}),\s*0x([0-9A-Fa-f]{1,2}),\s*0x([0-9A-Fa-f]{1,2})\]\s*,\s*name\s*=>\s*｢([^｣]+)｣\s*,\s*code\s*=>\s*'([^']*)'/g;

// Key: normalized form (used for dedupe). Value: [displayKey, hex, displayName, reseneCode].
const entries = new Map<string, [string, string, string, string]>();
let match: RegExpExecArray | null;
// biome-ignore lint/suspicious/noAssignInExpressions: standard global-regex loop pattern
while ((match = ENTRY_RE.exec(text)) !== null) {
  const [, stripped, rStr, gStr, bStr, displayName, reseneCode] = match;
  const r = Number.parseInt(rStr, 16);
  const g = Number.parseInt(gStr, 16);
  const b = Number.parseInt(bStr, 16);
  const hex = rgbaToHex({ r, g, b, a: 1 });
  const key = normalize(stripped);
  const existing = entries.get(key);
  if (existing !== undefined && existing[1] !== hex) {
    console.warn(
      `collision for "${key}": kept ${existing[1]} (${existing[0]}), ignored ${hex} (${stripped})`,
    );
    continue;
  }
  if (existing === undefined)
    entries.set(key, [stripped, hex, displayName.trim(), reseneCode.trim()]);
}

if (entries.size === 0) {
  throw new Error('No entries parsed from Resene source; regex may be out of date.');
}

// Sort alphabetically by key for a stable, readable emit.
const sorted = [...entries.values()].sort(([a], [b]) => a.localeCompare(b));

const SIMPLE_IDENT = /^[a-z_][a-z0-9_]*$/;
const formatKey = (k: string) => (SIMPLE_IDENT.test(k) ? k : JSON.stringify(k));

const body = sorted
  .map(([name, hex, displayName, code]) => {
    const base = `  ${formatKey(name)}: '${hex}',`;
    const comment = code ? `${displayName} [${code}]` : displayName;
    return comment ? `${base} // ${comment}` : base;
  })
  .join('\n');

const output = `import type { Palette } from '../types.js';
import { standardNormalize } from './normalize.js';

/**
 * Resene paint-catalog palette: ${sorted.length} entries from
 * Resene Paints (New Zealand), covering a large catalog of
 * named coatings, many with distinctly local flavor
 * ("Pohutukawa," "Acapulco," "Afghan Tan"). Popular reference
 * set for designers in Australia / New Zealand.
 *
 * Generated by scripts/generate-resene.ts — do not edit by hand.
 *
 * Source: Color::Names::Resene from @thundergnat/Color-Names
 * (Raku module). Each trailing comment carries the display form
 * of the name plus Resene's own Munsell-style code for the
 * chip (e.g. 'BR32-011-076') so a reader can cross-reference
 * against Resene's published materials. See NOTICE.md for
 * attribution details.
 *
 * Keys are the lowercase single-word form stripped from the
 * source's 'name-RESENE' identifiers ('treepoppy' for Tree
 * Poppy). Lookups still accept any casing or punctuation via
 * standardNormalize, so 'Tree Poppy', 'tree-poppy', and
 * 'treepoppy' all resolve identically.
 */
const reseneColors = {
${body}
} as const;

export type ReseneColorName = keyof typeof reseneColors;

/**
 * Resene palette with perceptual CIEDE2000 default: dense
 * coverage across the gamut, including saturated blues and
 * reds where ΔE2000 separates matches more consistently
 * than ΔE76.
 *
 * @example
 * identify('#e2813b', { palette: resene });    // 'treepoppy' (aka "Tree Poppy")
 * resolve('Tree Poppy', { palette: resene });  // '#e2813b'
 * resene.colors.acapulco;                      // '#75aa94'
 */
export const resene = {
  name: 'resene',
  colors: reseneColors,
  normalize: standardNormalize,
  defaultMetric: 'deltaE2000',
} as const satisfies Palette<ReseneColorName>;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${sorted.length} Resene colors to ${TARGET}`);
