#!/usr/bin/env bun
/**
 * Generate src/palettes/ntc.ts from Chirag Mehta's "Name That Color"
 * dataset, as redistributed by the MIT-licensed `colorjs/color-namer`
 * package. The upstream URL is pinned to a specific commit SHA so the
 * entry set can't silently shift under the palette.
 *
 * Names are kept in their source Title Case form (matching the
 * Crayola convention: "Navy Blue", not "navyblue") so `identify`
 * return values are display-ready. Hex values are lowercased with
 * a leading '#' so they match chromonym's canonical HexColor shape.
 *
 * Dedupe is by `standardNormalize(name)` just like x11/crayola, so
 * two source entries that normalize to the same key (none in the
 * current source) would collapse with a warning rather than silently.
 *
 * Usage: bun run scripts/generate-ntc.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SOURCE =
  'https://raw.githubusercontent.com/colorjs/color-namer/abb3d184ab63db9327908319cc45b55c91493bb7/lib/colors/ntc.js';
const TARGET = resolve(import.meta.dirname, '../src/palettes/ntc.ts');

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

type RawEntry = { name: string; hex: string };

const response = await fetch(SOURCE);
if (!response.ok) {
  throw new Error(`Failed to fetch ${SOURCE}: ${response.status}`);
}
const text = await response.text();

// The file is `module.exports = [ {...}, {...} ]` with no trailing
// semicolon. Strip the assignment; what remains is valid JSON.
const jsonText = text.replace(/^module\.exports\s*=\s*/, '').trim();
const raw = JSON.parse(jsonText) as RawEntry[];

// Key: normalized form (used for dedupe). Value: [displayName, hex].
const entries = new Map<string, [string, string]>();
for (const { name, hex } of raw) {
  const display = name.trim();
  const canonicalHex = `#${hex.toLowerCase()}`;
  const key = normalize(display);
  const existing = entries.get(key);
  if (existing !== undefined && existing[1] !== canonicalHex) {
    console.warn(
      `collision for "${key}": kept ${existing[1]} (${existing[0]}), ignored ${canonicalHex} (${display})`,
    );
    continue;
  }
  if (existing === undefined) entries.set(key, [display, canonicalHex]);
}

const sorted = [...entries.values()].sort(([a], [b]) => a.localeCompare(b));

// Match biome's preferred style: unquoted simple identifier keys, quoted otherwise.
// JSON.stringify produces a double-quoted string with all necessary escapes,
// which is valid TS/JS object-literal syntax (covers apostrophes in names
// like "Purple Mountain's Majesty").
const SIMPLE_IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;
const formatKey = (k: string) => (SIMPLE_IDENT.test(k) ? k : JSON.stringify(k));

const body = sorted.map(([name, hex]) => `  ${formatKey(name)}: '${hex}',`).join('\n');

const output = `import type { Palette } from '../types.js';
import { standardNormalize } from './normalize.js';

/**
 * Name That Color (NTC) palette: Chirag Mehta's broad color-name
 * dataset. ${sorted.length} entries covering design, fashion, and
 * common hardware/UI colors that CSS and X11 don't name.
 *
 * Generated by scripts/generate-ntc.ts — do not edit by hand.
 *
 * Source: upstream dataset is \`lib/colors/ntc.js\` from
 * MIT-licensed \`colorjs/color-namer\`, which itself redistributes
 * Chirag Mehta's "Name That Color" script (chir.ag/projects/ntc).
 * See NOTICE.md for full attribution.
 *
 * Keys are display-ready Title Case ("Navy Blue"); lookups still
 * accept any casing / punctuation via standardNormalize.
 */
const ntcColors = {
${body}
} as const;

export type NtcColorName = keyof typeof ntcColors;

/**
 * Name That Color (NTC): Chirag Mehta's broad color-name dataset.
 * ${sorted.length} entries covering design, fashion, and common
 * hardware / UI colors that CSS and X11 don't name. Default metric
 * is CIEDE2000 for best ranking across the dense saturated regions;
 * override per call (e.g. \`'deltaEok'\`, \`'euclidean-srgb'\`) for
 * interactive UIs that scrub many colors per second.
 *
 * @example
 * identify('#bada55', { palette: ntc });                   // 'Conifer'
 * resolve('International Klein Blue', { palette: ntc });   // '#002fa7'
 * ntc.colors.Stratos;                                      // '#000741'
 */
export const ntc = {
  name: 'ntc',
  colors: ntcColors,
  normalize: standardNormalize,
  defaultMetric: 'deltaE2000',
} as const satisfies Palette<NtcColorName>;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${sorted.length} NTC colors to ${TARGET}`);
