#!/usr/bin/env bun
/**
 * Generate src/palettes/nbs.ts from the Color-Names Raku module's
 * NBS dataset by @thundergnat on GitHub.
 *
 * The NBS (National Bureau of Standards, now NIST) system is the
 * 1955 ISCC-NBS Method of Designating Colors — 267 named blocks
 * ("Vivid Pink", "Grayish Yellowish Brown"). The same vocabulary
 * is covered by chromonym's `isccNbs` palette (Paul Centore's
 * Munsell-centroid digitization), but the upstream NBS module
 * ships DIFFERENT sRGB approximations for the same names (e.g.
 * Vivid Pink is #ffb5ba here vs #fd7992 in Centore). Both are
 * legitimate digitizations; ship as a separate palette so users
 * can compare or pick based on which reference matches their
 * workflow.
 *
 * Canonical keys: stripped lowercase raku form ('vividpink' for
 * 'Vivid Pink'), matching the Resene palette's convention. This
 * also visually distinguishes NBS queries from the sentence-case
 * `isccNbs` palette's keys. Display names go into trailing
 * comments for human readers.
 *
 * Usage: bun run scripts/generate-nbs.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { rgbaToHex } from '../src/conversions/hex.js';

const SOURCE =
  'https://raw.githubusercontent.com/thundergnat/Color-Names/refs/heads/main/lib/Color/Names/NBS.rakumod';
const TARGET = resolve(import.meta.dirname, '../src/palettes/nbs.ts');

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const response = await fetch(SOURCE);
if (!response.ok) {
  throw new Error(`Failed to fetch ${SOURCE}: ${response.status}`);
}
const text = await response.text();

// 'brilliantblue-NBS' => { rgb => [0x49, 0x97, 0xD0], name => ｢Brilliant Blue｣ },
const ENTRY_RE =
  /'([a-z0-9]+)-NBS'\s*=>\s*\{\s*rgb\s*=>\s*\[0x([0-9A-Fa-f]{1,2}),\s*0x([0-9A-Fa-f]{1,2}),\s*0x([0-9A-Fa-f]{1,2})\]\s*,\s*name\s*=>\s*｢([^｣]+)｣/g;

// Key: normalized form (used for dedupe). Value: [displayKey, hex, displayName].
const entries = new Map<string, [string, string, string]>();
let match: RegExpExecArray | null;
// biome-ignore lint/suspicious/noAssignInExpressions: standard global-regex loop pattern
while ((match = ENTRY_RE.exec(text)) !== null) {
  const [, stripped, rStr, gStr, bStr, displayName] = match;
  const r = Number.parseInt(rStr, 16);
  const g = Number.parseInt(gStr, 16);
  const b = Number.parseInt(bStr, 16);
  const hex = rgbaToHex({ r, g, b, a: 1 });
  const key = normalize(stripped);
  const existing = entries.get(key);
  if (existing !== undefined && existing[1] !== hex) {
    console.warn(
      `collision for "${key}": kept ${existing[1]} (${existing[0]}), ignored ${hex} (${stripped})`,
    );
    continue;
  }
  if (existing === undefined) entries.set(key, [stripped, hex, displayName.trim()]);
}

if (entries.size === 0) {
  throw new Error('No entries parsed from NBS source; regex may be out of date.');
}

const sorted = [...entries.values()].sort(([a], [b]) => a.localeCompare(b));

const SIMPLE_IDENT = /^[a-z_][a-z0-9_]*$/;
const formatKey = (k: string) => (SIMPLE_IDENT.test(k) ? k : JSON.stringify(k));

const body = sorted
  .map(([name, hex, displayName]) => {
    const base = `  ${formatKey(name)}: '${hex}',`;
    return displayName ? `${base} // ${displayName}` : base;
  })
  .join('\n');

const output = `import type { Palette } from '../types.js';
import { standardNormalize } from './normalize.js';

/**
 * NBS palette: a second digitization of the ISCC-NBS Method of
 * Designating Colors (1955, US National Bureau of Standards, now
 * NIST), ${sorted.length} entries covering the same named color blocks
 * as chromonym's \`isccNbs\` palette but with different sRGB
 * approximations. "Vivid Pink" is \`#ffb5ba\` here versus
 * \`#fd7992\` in \`isccNbs\` (Centore's Munsell-centroid version).
 *
 * Generated by scripts/generate-nbs.ts — do not edit by hand.
 *
 * Source: Color::Names::NBS from @thundergnat/Color-Names (Raku
 * module). See NOTICE.md for attribution and the relationship to
 * the \`isccNbs\` palette.
 *
 * Keys are the lowercase single-word form stripped from the
 * source's '<name>-NBS' identifiers ('brilliantblue' for
 * 'Brilliant Blue'). Lookups still accept any casing or
 * punctuation via standardNormalize. This key format matches the
 * Resene palette's convention and visually distinguishes NBS
 * queries from the sentence-case \`isccNbs\` palette.
 */
const nbsColors = {
${body}
} as const;

export type NbsColorName = keyof typeof nbsColors;

/**
 * NBS, alternate digitization of the 1955 ISCC-NBS naming
 * system (${sorted.length} entries). Same named-block vocabulary
 * as chromonym's \`isccNbs\` palette (average ΔE2000 ~4.6 across
 * shared names, max 31); matches the 1955 physical chip book
 * and covers the 7 out-of-gamut blocks \`isccNbs\` leaves as
 * gaps. Default metric CIEDE2000.
 *
 * @example
 * identify('#ffb5ba', { palette: nbs });           // 'vividpink'
 * resolve('Brilliant Blue', { palette: nbs });     // '#4997d0'
 * nbs.colors.grayishpurplishred;                   // '#915f6d'
 */
export const nbs = {
  name: 'nbs',
  colors: nbsColors,
  normalize: standardNormalize,
  defaultMetric: 'deltaE2000',
} as const satisfies Palette<NbsColorName>;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${sorted.length} NBS colors to ${TARGET}`);
