#!/usr/bin/env bun
/**
 * Generate src/palettes/fs595c.ts from the Color-Names Raku module's
 * FS595C dataset by @thundergnat on GitHub.
 *
 * FS595C ("Federal Standard 595C") is the US Federal Government's
 * paint-color specification, widely used for military, aviation, and
 * government equipment. Each entry has a 5-digit code and, sometimes,
 * a common name ("Insignia Red", "Air Superiority Blue"). Common
 * names are NOT unique (the code book has 18 different "Green"s, 11
 * "Tan"s, etc.), so we use the codes as canonical keys and discard
 * the common-name column.
 *
 * Canonical key format: `'FS ${code}'` (e.g. `'FS 11136'`). The `FS`
 * prefix makes `identify` return values self-documenting instead of
 * returning a bare 5-digit number that could be confused with any
 * other numeric-coded palette.
 *
 * Source file is Raku; it uses the `｢｣` delimiters for strings and
 * `0xHH` hex literals for RGB bytes. We regex-extract the code and
 * the three hex bytes per entry; everything else in the .rakumod
 * file is ignored.
 *
 * Usage: bun run scripts/generate-fs595c.ts
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SOURCE =
  'https://raw.githubusercontent.com/thundergnat/Color-Names/refs/heads/main/lib/Color/Names/FS595C.rakumod';
const TARGET = resolve(import.meta.dirname, '../src/palettes/fs595c.ts');

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

const response = await fetch(SOURCE);
if (!response.ok) {
  throw new Error(`Failed to fetch ${SOURCE}: ${response.status}`);
}
const text = await response.text();

// Per-line regex: '10032-FS595C' => { rgb => [0x37, 0x27, 0x26], name => ｢10032｣, code => ｢｣ },
const ENTRY_RE =
  /'(\d+)-FS595C'\s*=>\s*\{\s*rgb\s*=>\s*\[0x([0-9A-Fa-f]{1,2}),\s*0x([0-9A-Fa-f]{1,2}),\s*0x([0-9A-Fa-f]{1,2})\]/g;

const toHexByte = (s: string) => s.padStart(2, '0').toLowerCase();

// Key: normalized form (used for dedupe). Value: [displayKey, hex].
const entries = new Map<string, [string, string]>();
let match: RegExpExecArray | null;
// biome-ignore lint/suspicious/noAssignInExpressions: standard global-regex loop pattern
while ((match = ENTRY_RE.exec(text)) !== null) {
  const [, code, r, g, b] = match;
  const displayKey = `FS ${code}`;
  const hex = `#${toHexByte(r)}${toHexByte(g)}${toHexByte(b)}`;
  const key = normalize(displayKey);
  const existing = entries.get(key);
  if (existing !== undefined && existing[1] !== hex) {
    console.warn(
      `collision for "${key}": kept ${existing[1]} (${existing[0]}), ignored ${hex} (${displayKey})`,
    );
    continue;
  }
  if (existing === undefined) entries.set(key, [displayKey, hex]);
}

if (entries.size === 0) {
  throw new Error('No entries parsed from FS595C source; regex may be out of date.');
}

// Sort numerically by FS code so the emitted file reads in code order
// (matches how these are organized in the federal spec itself).
const sorted = [...entries.values()].sort(([a], [b]) => {
  const na = Number.parseInt(a.slice(3), 10);
  const nb = Number.parseInt(b.slice(3), 10);
  return na - nb;
});

// JSON.stringify handles the space in 'FS 11136' and any embedded
// punctuation robustly.
const SIMPLE_IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;
const formatKey = (k: string) => (SIMPLE_IDENT.test(k) ? k : JSON.stringify(k));

const body = sorted.map(([name, hex]) => `  ${formatKey(name)}: '${hex}',`).join('\n');

const output = `import type { Palette } from '../types.js';
import { standardNormalize } from './normalize.js';

/**
 * Federal Standard 595C (FS595C) palette: US Federal Government
 * paint-color specification, widely used in military, aviation,
 * and government-equipment coatings. ${sorted.length} entries.
 *
 * Generated by scripts/generate-fs595c.ts — do not edit by hand.
 *
 * Source: upstream dataset is Color::Names::FS595C from
 * @thundergnat/Color-Names (Raku module), which digitizes the
 * public Federal Standard 595 paint chips. See NOTICE.md for
 * attribution.
 *
 * Keys are the 5-digit FS codes prefixed with 'FS ' (e.g.
 * 'FS 11136'). Common names like "Insignia Red" are NOT used as
 * keys because the spec reuses many of them across different
 * chips (18 different "Green"s, 11 "Tan"s, etc.). Lookups still
 * accept any casing and punctuation via standardNormalize, so
 * 'fs11136', 'FS-11136', and 'FS 11136' all resolve identically.
 */
const fs595cColors = {
${body}
} as const;

export type Fs595cColorName = keyof typeof fs595cColors;

/**
 * FS595C palette with perceptual CIEDE2000 default: small (589
 * entries) and spread across the spectrum, with dense coverage
 * in olive/tan/grey regions where ΔE76 is a known weak spot for
 * military coatings.
 *
 * @example
 * identify('#a32b25', { palette: fs595c });         // 'FS 11136' (aka "Insignia Red")
 * resolve('FS 11136', { palette: fs595c });         // '#a32b25'
 * resolve('fs-11136', { palette: fs595c });         // '#a32b25' (normalize strips casing + dash)
 * fs595c.colors['FS 10032'];                        // '#372726'
 */
export const fs595c = {
  name: 'fs595c',
  colors: fs595cColors,
  normalize: standardNormalize,
  defaultMetric: 'deltaE2000',
} as const satisfies Palette<Fs595cColorName>;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${sorted.length} FS595C colors to ${TARGET}`);
