#!/usr/bin/env bun
/**
 * Generate src/palettes/x11.ts from the X.Org rgb.txt file.
 *
 * Reads from /usr/share/X11/rgb.txt (X11 / X.Org public-domain color list).
 * Humanizes names to lowercase with word spaces ("antique white 1" rather
 * than "antiquewhite1") so `identify` return values are display-ready, then
 * dedupes on the shape `standardNormalize` would produce ("antiquewhite1")
 * so that source entries like "AntiqueWhite1" and "antique white 1" fold
 * together.
 *
 * Usage: bun run scripts/generate-x11.ts
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const SOURCE = '/usr/share/X11/rgb.txt';
const TARGET = resolve(import.meta.dirname, '../src/palettes/x11.ts');

const toHex = (r: number, g: number, b: number): string =>
  `#${[r, g, b].map((n) => n.toString(16).padStart(2, '0')).join('')}`;

// CamelCase → camel case; letter-digit boundaries get a space too.
// Produces lowercase with single-spaced words suitable as a display key.
const humanize = (name: string) =>
  name
    .replace(/([a-z])([A-Z])/g, '$1 $2')
    .replace(/([A-Za-z])(\d)/g, '$1 $2')
    .replace(/(\d)([A-Za-z])/g, '$1 $2')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();

const normalize = (s: string) => s.replace(/[^a-z0-9]/g, '');

const raw = readFileSync(SOURCE, 'utf8');

// Key: normalized form (used for dedupe). Value: [displayName, hex].
const entries = new Map<string, [string, string]>();
for (const line of raw.split('\n')) {
  if (!line || line.startsWith('!')) continue;
  const match = /^\s*(\d+)\s+(\d+)\s+(\d+)\s+(.+?)\s*$/.exec(line);
  if (!match) continue;
  const [, r, g, b, rawName] = match;
  const display = humanize(rawName);
  const normalized = normalize(display);
  const hex = toHex(Number(r), Number(g), Number(b));
  const existing = entries.get(normalized);
  if (existing !== undefined && existing[1] !== hex) {
    console.warn(`collision for "${normalized}": kept ${existing[1]}, ignored ${hex}`);
    continue;
  }
  if (existing === undefined) entries.set(normalized, [display, hex]);
}

const sorted = [...entries.values()].sort(([a], [b]) => a.localeCompare(b));

// Match biome's preferred style: unquoted simple identifier keys, quoted otherwise.
const SIMPLE_IDENT = /^[a-z_][a-z0-9_]*$/;
const formatKey = (k: string) => (SIMPLE_IDENT.test(k) ? k : `'${k}'`);

const body = sorted.map(([name, hex]) => `  ${formatKey(name)}: '${hex}',`).join('\n');

const output = `import type { Palette } from '../types.js';
import { standardNormalize } from './normalize.js';

/**
 * X11 / X.Org named colors (from rgb.txt, public domain). ${sorted.length} entries.
 * Generated by scripts/generate-x11.ts — do not edit by hand.
 * Keys are display-ready (spaced, lowercase); lookups still accept any
 * casing / punctuation since standardNormalize strips non-alphanumerics.
 */
const x11Colors = {
${body}
} as const;

export type X11ColorName = keyof typeof x11Colors;

/**
 * Default metric note: x11 has 658 entries including dense numbered ramps
 * (gray 0-100, dark slate gray 1-4, etc). ΔE76 is chosen for speed — at
 * ~5 µs per identify vs ~90 µs for ΔE2000 — which matters for interactive
 * UIs that scrub many colors per second.
 *
 * The tradeoff: ΔE76's known weakness in saturated blue/purple can pick a
 * perceptually-suboptimal neighbor for colors in that region. For those
 * inputs, override per-call with a perceptually-uniform metric:
 *   identify(hex, { palette: x11, metric: 'deltaEok' })    // ~5 µs
 *   identify(hex, { palette: x11, metric: 'deltaE2000' })  // ~90 µs
 */
export const x11 = {
  name: 'x11',
  colors: x11Colors,
  normalize: standardNormalize,
  defaultMetric: 'deltaE76',
} as const satisfies Palette<X11ColorName>;
`;

writeFileSync(TARGET, output, 'utf8');
console.log(`Wrote ${sorted.length} X11 colors to ${TARGET}`);
