import type { Palette } from '../types.js';
import { standardNormalize } from './normalize.js';

/**
 * ISCC-NBS palette (260 entries): the Inter-Society
 * Color Council / National Bureau of Standards 1955 method of
 * designating colors, which partitions the Munsell color solid
 * into named blocks like 'vivid pink', 'strong purplish red',
 * 'dark yellowish brown'. Widely used in color-science literature
 * as a standard vocabulary for consistent color communication.
 *
 * Source: Paul Centore's Munsell Colour Science for Painters
 * site, ISCCNBSSystem.html — sRGB centroids of each named block.
 * See NOTICE.md for attribution and license notes.
 *
 * Keys are sentence-case display names ('Vivid pink') matching
 * the ISCC-NBS vocabulary. Lookups still accept any casing or
 * punctuation via standardNormalize, so 'vivid-pink' and
 * 'VIVID PINK' both resolve identically.
 */
const isccNbsColors = {
  Black: '#2b292b',
  'Blackish blue': '#1e2531',
  'Blackish green': '#1f2a2a',
  'Blackish purple': '#2f2231',
  'Blackish red': '#332127',
  'Bluish black': '#24272e',
  'Bluish gray': '#838793',
  'Bluish white': '#e1e1f1',
  'Brilliant blue': '#419ded',
  'Brilliant bluish green': '#35d7ce',
  'Brilliant green': '#49d0a3',
  'Brilliant greenish blue': '#2dbce2',
  'Brilliant greenish yellow': '#e9dc55',
  'Brilliant orange yellow': '#ffbe50',
  'Brilliant purple': '#ce8ce3',
  'Brilliant purplish blue': '#8088e2',
  'Brilliant purplish pink': '#fca1e7',
  'Brilliant violet': '#987fdc',
  'Brilliant yellow': '#f7ce50',
  'Brilliant yellow green': '#c3df69',
  'Brilliant yellowish green': '#87d989',
  'Brownish black': '#2b211e',
  'Brownish gray': '#605251',
  'Brownish orange': '#b26633',
  'Brownish pink': '#cbafa7',
  'Dark blue': '#173459',
  'Dark bluish gray': '#50545f',
  'Dark bluish green': '#154b4d',
  'Dark brown': '#442112',
  'Dark gray': '#585458',
  'Dark grayish blue': '#323f4e',
  'Dark grayish brown': '#3e2c28',
  'Dark grayish green': '#394746',
  'Dark grayish olive': '#35301c',
  'Dark grayish olive green': '#2f3326',
  'Dark grayish purple': '#513f51',
  'Dark grayish red': '#53383e',
  'Dark grayish reddish brown': '#43292a',
  'Dark grayish yellow': '#a99066',
  'Dark grayish yellowish brown': '#4d3d33',
  'Dark green': '#164e3d',
  'Dark greenish blue': '#134a60',
  'Dark greenish gray': '#545858',
  'Dark greenish yellow': '#9e953c',
  'Dark olive': '#352e0a',
  'Dark olive brown': '#3f2c10',
  'Dark olive green': '#20340b',
  'Dark orange yellow': '#c38639',
  'Dark pink': '#c5808a',
  'Dark purple': '#563762',
  'Dark purplish blue': '#222248',
  'Dark purplish gray': '#5c525e',
  'Dark purplish pink': '#c67d9d',
  'Dark purplish red': '#6e294c',
  'Dark red': '#742434',
  'Dark reddish brown': '#461d1e',
  'Dark reddish gray': '#5d4e53',
  'Dark reddish orange': '#a2402b',
  'Dark reddish purple': '#5f3458',
  'Dark violet': '#34254d',
  'Dark yellow': '#b08f42',
  'Dark yellowish brown': '#50341a',
  'Dark yellowish green': '#2f5d3a',
  'Dark yellowish pink': '#c9807e',
  'Deep blue': '#113074',
  'Deep brown': '#571a07',
  'Deep greenish yellow': '#a29812',
  'Deep orange': '#c26012',
  'Deep orange yellow': '#d08511',
  'Deep pink': '#e66980',
  'Deep purple': '#652277',
  'Deep purplish blue': '#2a286f',
  'Deep purplish pink': '#df6aac',
  'Deep purplish red': '#881055',
  'Deep red': '#87122d',
  'Deep reddish brown': '#610f12',
  'Deep reddish orange': '#af3318',
  'Deep reddish purple': '#761a6a',
  'Deep violet': '#3c1668',
  'Deep yellow': '#b88f16',
  'Deep yellow green': '#486c0e',
  'Deep yellowish brown': '#673f0b',
  'Deep yellowish green': '#176a1e',
  'Deep yellowish pink': '#ef6366',
  'Grayish blue': '#54687f',
  'Grayish brown': '#674f48',
  'Grayish green': '#61716e',
  'Grayish greenish yellow': '#beb584',
  'Grayish olive': '#5d553f',
  'Grayish olive green': '#545947',
  'Grayish pink': '#cbadb7',
  'Grayish purple': '#7b667e',
  'Grayish purplish blue': '#494d71',
  'Grayish purplish pink': '#c7a3b9',
  'Grayish purplish red': '#945c73',
  'Grayish red': '#985d62',
  'Grayish reddish brown': '#6c4d4b',
  'Grayish reddish orange': '#b97565',
  'Grayish reddish purple': '#86627e',
  'Grayish violet': '#584e72',
  'Grayish yellow': '#c8b18b',
  'Grayish yellow green': '#979a85',
  'Grayish yellowish brown': '#7e695d',
  'Grayish yellowish pink': '#cbacac',
  'Greenish black': '#212626',
  'Greenish gray': '#848888',
  'Greenish white': '#e0e2e5',
  'Light blue': '#73a4dc',
  'Light bluish gray': '#b7b8c6',
  'Light bluish green': '#5fabab',
  'Light brown': '#ad7c63',
  'Light brownish gray': '#928281',
  'Light gray': '#bdb7bf',
  'Light grayish brown': '#997f75',
  'Light grayish olive': '#8e856f',
  'Light grayish purplish red': '#b2879b',
  'Light grayish red': '#b4888d',
  'Light grayish reddish brown': '#9e7f7a',
  'Light grayish yellowish brown': '#b49b8d',
  'Light green': '#6fac95',
  'Light greenish blue': '#65a8c3',
  'Light greenish gray': '#babec1',
  'Light greenish yellow': '#e9dd8a',
  'Light olive': '#8b7d2e',
  'Light olive brown': '#997736',
  'Light olive gray': '#8f877f',
  'Light orange': '#fbaf82',
  'Light orange yellow': '#fcc27c',
  'Light pink': '#f8c3ce',
  'Light purple': '#bc93cc',
  'Light purplish blue': '#8991cb',
  'Light purplish gray': '#c3b7c6',
  'Light purplish pink': '#f5b2db',
  'Light reddish brown': '#ac7a73',
  'Light reddish purple': '#bd80ae',
  'Light violet': '#9b8cca',
  'Light yellow': '#f4d284',
  'Light yellow green': '#cedb9f',
  'Light yellowish brown': '#c49a74',
  'Light yellowish green': '#9cc69c',
  'Light yellowish pink': '#f8c4b6',
  'Medium gray': '#8a8489',
  'Moderate blue': '#34689e',
  'Moderate bluish green': '#297a7b',
  'Moderate brown': '#724a38',
  'Moderate green': '#337762',
  'Moderate greenish blue': '#2a7691',
  'Moderate greenish yellow': '#c0b55e',
  'Moderate olive': '#64591a',
  'Moderate olive brown': '#705420',
  'Moderate olive green': '#495b22',
  'Moderate orange': '#de8d5c',
  'Moderate orange yellow': '#e7a75d',
  'Moderate pink': '#e2a3ae',
  'Moderate purple': '#875e96',
  'Moderate purplish blue': '#4d4e87',
  'Moderate purplish pink': '#de98bf',
  'Moderate purplish red': '#ab4b74',
  'Moderate red': '#b14955',
  'Moderate reddish brown': '#7d423b',
  'Moderate reddish orange': '#cd6952',
  'Moderate reddish purple': '#965888',
  'Moderate violet': '#5c4985',
  'Moderate yellow': '#d2af63',
  'Moderate yellow green': '#8b9a5f',
  'Moderate yellowish brown': '#886648',
  'Moderate yellowish green': '#669069',
  'Moderate yellowish pink': '#e2a698',
  'Olive black': '#23211c',
  'Olive gray': '#58514a',
  'Pale blue': '#91a2bb',
  'Pale green': '#94a6a3',
  'Pale greenish yellow': '#e6dcab',
  'Pale orange yellow': '#eec6a6',
  'Pale pink': '#efd1dc',
  'Pale purple': '#ad97b3',
  'Pale purplish blue': '#8e92b7',
  'Pale purplish pink': '#ebc8df',
  'Pale reddish purple': '#ad89a5',
  'Pale violet': '#9a90b5',
  'Pale yellow': '#efd7b2',
  'Pale yellow green': '#d7d7c1',
  'Pale yellowish pink': '#f1d3d1',
  'Pinkish gray': '#c7b6bd',
  'Pinkish white': '#efdde5',
  'Purplish black': '#2b2630',
  'Purplish gray': '#8f8490',
  'Purplish white': '#ebdfef',
  'Reddish black': '#30262b',
  'Reddish gray': '#928186',
  'Strong blue': '#276cbd',
  'Strong bluish green': '#0d8f82',
  'Strong brown': '#8a4416',
  'Strong green': '#158a66',
  'Strong greenish blue': '#1385af',
  'Strong greenish yellow': '#c4b827',
  'Strong olive green': '#2c5506',
  'Strong orange': '#ea8127',
  'Strong orange yellow': '#f0a121',
  'Strong pink': '#f48fa0',
  'Strong purple': '#9352a8',
  'Strong purplish blue': '#5359b5',
  'Strong purplish pink': '#f483cd',
  'Strong purplish red': '#b83773',
  'Strong red': '#bf344b',
  'Strong reddish brown': '#8b1c0e',
  'Strong reddish orange': '#db5d3b',
  'Strong reddish purple': '#a74994',
  'Strong violet': '#61419c',
  'Strong yellow': '#d9ae2f',
  'Strong yellow green': '#82a12b',
  'Strong yellowish brown': '#9e671d',
  'Strong yellowish green': '#39964a',
  'Strong yellowish pink': '#f59080',
  'Very dark bluish green': '#0a2d2e',
  'Very dark green': '#0c2e24',
  'Very dark greenish blue': '#0b2c3b',
  'Very dark purple': '#371b41',
  'Very dark purplish red': '#431432',
  'Very dark red': '#481127',
  'Very dark reddish purple': '#3f183c',
  'Very dark yellowish green': '#10361a',
  'Very deep purple': '#460a55',
  'Very deep purplish red': '#54063c',
  'Very deep red': '#5c0625',
  'Very deep reddish purple': '#4f094a',
  'Very deep yellowish green': '#054208',
  'Very light blue': '#99c6f9',
  'Very light bluish green': '#98e1e0',
  'Very light green': '#a6e2ca',
  'Very light greenish blue': '#94d6ef',
  'Very light purple': '#e4b9f3',
  'Very light purplish blue': '#b7c0f8',
  'Very light violet': '#c9baf8',
  'Very light yellowish green': '#c5edc4',
  'Very pale blue': '#c2d2ec',
  'Very pale green': '#c7d9d6',
  'Very pale purple': '#e0cbeb',
  'Very pale purplish blue': '#c5c9f0',
  'Very pale violet': '#d0c6ef',
  'Vivid blue': '#1b5cd7',
  'Vivid bluish green': '#13fcd5',
  'Vivid green': '#23eaa5',
  'Vivid greenish yellow': '#ebdd21',
  'Vivid orange': '#f7760b',
  'Vivid pink': '#fd7992',
  'Vivid purple': '#b935d5',
  'Vivid purplish blue': '#4436d1',
  'Vivid purplish red': '#dd2388',
  'Vivid red': '#d51c3c',
  'Vivid reddish orange': '#e83b1b',
  'Vivid reddish purple': '#d429b9',
  'Vivid violet': '#7931d3',
  'Vivid yellow': '#f1bf15',
  'Vivid yellow green': '#a7dc26',
  'Vivid yellowish green': '#3fd740',
  'Vivid yellowish pink': '#fd7e5d',
  White: '#e7e1e9',
  'Yellowish gray': '#c6b9b1',
  'Yellowish white': '#eedfda',
} as const;

export type IsccNbsColorName = keyof typeof isccNbsColors;

/**
 * ISCC-NBS Method of Designating Colors (1955, 260
 * entries): Munsell-partitioned named blocks like 'Vivid pink'
 * and 'Dark yellowish brown'. sRGB centroids computed by Paul
 * Centore. For the alternate digitization that matches the
 * 1955 physical chip book, see chromonym's `nbs` palette.
 * Default metric CIEDE2000.
 *
 * @example
 * identify('#fd7992', { palette: isccNbs });           // 'Vivid pink'
 * resolve('dark yellowish green', { palette: isccNbs }); // '#2f5d3a'
 * isccNbs.colors['Vivid pink'];                          // '#fd7992'
 */
export const isccNbs = {
  name: 'isccNbs',
  colors: isccNbsColors,
  normalize: standardNormalize,
  defaultMetric: 'deltaE2000',
} as const satisfies Palette<IsccNbsColorName>;
